### ISSUE TITLE
[Question] Why fast?

### ISSUE THREAD

**Issue by Kikobeats** [mcollina/fast-json-parse#1]
I don't see the point that makes this library faster than use JSON.parse interface.

Maybe is related with the fact that you don't throw errors?

On the other hand, you say:

```
Depending on your application, the constructor mode can be faster or slower.
```

How to know this?

**Comment by mcollina** [comment]
> Maybe is related with the fact that you don't throw errors?

It is the right way to handle parsing error, and have your function optimize. So, that's why it's fast.

>  Depending on your application, the constructor mode can be faster or slower.

A bit longer to answer, and I am flying away tomorrow for vacation. I'll leave this open and get back when I'm back. But the end line is "benchmark".

**Comment by Kikobeats** [comment]
Enjoy your vacations! ⛵

btw I run benchmark three and I don't see a appreciate difference:

```
~/Downloads/fast-json-parse master
❯ node benchmark.js
literal x 29,739 ops/sec ±6.33% (74 runs sampled)
Parse class x 19,599 ops/sec ±16.66% (61 runs sampled)
Parse wrapped x 25,508 ops/sec ±7.45% (65 runs sampled)
json-parse-safe x 26,420 ops/sec ±8.10% (67 runs sampled)
setter x 26,024 ops/sec ±9.59% (62 runs sampled)
try catch here x 29,457 ops/sec ±6.66% (72 runs sampled)
Fastest is literal

~/Downloads/fast-json-parse master 34s
❯ node benchmark.js
literal x 35,158 ops/sec ±2.64% (80 runs sampled)
Parse class x 33,112 ops/sec ±8.34% (77 runs sampled)
Parse wrapped x 35,999 ops/sec ±2.20% (82 runs sampled)
json-parse-safe x 36,464 ops/sec ±1.86% (85 runs sampled)
setter x 35,430 ops/sec ±2.84% (81 runs sampled)
try catch here x 35,047 ops/sec ±1.76% (86 runs sampled)
Fastest is json-parse-safe

~/Downloads/fast-json-parse master 33s
❯ node benchmark.js
literal x 34,898 ops/sec ±3.11% (79 runs sampled)
Parse class x 34,463 ops/sec ±4.18% (83 runs sampled)
Parse wrapped x 36,619 ops/sec ±1.94% (82 runs sampled)
json-parse-safe x 34,333 ops/sec ±8.01% (81 runs sampled)
setter x 36,048 ops/sec ±2.25% (80 runs sampled)
try catch here x 32,759 ops/sec ±4.27% (79 runs sampled)
Fastest is Parse wrapped
```

PS: What about `fast-json-stringify`? 😛

**Comment by mcollina** [comment]
Interesting. This was extracted from a project where json-parse-safe was not performing on par. Might be just very use-case specific.
I've patched the README anyway.
