### ISSUE TITLE
WTF!!!!!!

### ISSUE THREAD

**Issue by art-emm** [mcollina/fast-json-parse#2]
function Parse (data) {
4     if (!(this instanceof Parse)) {
5       return new Parse(data)
6     }
7     this.err = null
8     this.value = null
9     try {
10      this.value = JSON.parse(data) ///WFT? FAST? ARE you serious??
11    } catch (err) {
12      this.err = err
13    }
14  }

**Comment by mcollina** [comment]
Thanks for reaching out. I will close this issue as highly unrelevant. Feel free to open a new one with proper language. Thanks.

**Comment by slidenerd** [comment]
god I wish I could just teleport to your computer when you were away login with the magic password and delete your GitHub account, is this a troll?
