### ISSUE TITLE
Explain in what way is  this faster although it use's the original JSON.parse

### ISSUE THREAD

**Issue by jodevsa** [mcollina/fast-json-parse#4]
Fast compared to what ? 

It use's the original JSON.parse ?

**Comment by mcollina** [comment]
When you use JSON.parse, you must use Try catch is slow in all version of Node prior to 7, I will update the README.

**Comment by jodevsa** [comment]
That's interesting to know, but you'r using try catch also ?
`  try {
    this.value = JSON.parse(data)
  } catch (err) {
    this.err = err
  }`

**Comment by mcollina** [comment]
Yes, but the deoptimization is limited to that function. While if you use try/catch within a larger function, it will impact all code in it.

**Comment by jodevsa** [comment]
Thanks, interesting to know again (Y)

**Comment by jodevsa** [comment]
imma post some resources about this behavior for  new comers :
http://www.lighthouselogic.com/try-catch-performance-in-node-js/
https://stackoverflow.com/questions/43845361/why-try-catch-block-faster-than-normal-in-nodejs-v7

**Comment by mcollina** [comment]
You might want to read https://www.nearform.com/blog/node-js-is-getting-a-new-v8-with-turbofan/ as well.
